version: 2

jobs:
  32bit:
    docker:
      - image: quay.io/pypa/manylinux1_i686
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: /opt/python/cp36-cp36m/bin/pip install -e .[test]
      - run:
          name: Run tests
          command: /opt/python/cp36-cp36m/bin/python setup.py test

workflows:
  version: 2
  build_and_test:
    jobs:
      - 32bit
